[package]
name = "sygaldry"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
cipher = "0.4.4"
jiff = { version = "0.2.16", default-features = false, features = ["alloc", "tzdb-bundle-always"] }
